apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resume-screener-ingress
  namespace: resume-screener-ns
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: resume-screener.local # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: resume-screener-svc
            port:
              number: 80
