apiVersion: v1
kind: Service
metadata:
  name: resume-screener-svc
  namespace: resume-screener-ns
spec:
  type: LoadBalancer
  selector:
    app: resume-screener
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
